# PyTorch ML library

An open source machine learning framework that accelerates the path from research prototyping to production deployment.

![PyTorch](https://upload.wikimedia.org/wikipedia/commons/9/96/Pytorch_logo.png)

In [ ]:
# conda install pytorch torchvision cudatoolkit=10.1 -c pytorch

## Cheat Sheet

* https://pytorch.org/tutorials/beginner/ptcheat.html

### https://pytorch.org/get-started/locally/

In [1]:
from __future__ import print_function
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.8662, 0.9206, 0.8438],
        [0.0829, 0.1600, 0.6955],
        [0.9328, 0.6095, 0.7701],
        [0.7732, 0.6909, 0.3331],
        [0.2956, 0.0922, 0.5187]])


In [2]:
torch.cuda.is_available()

True

In [ ]:
# Cloud Partner Alternatives (mosty paid)
# https://pytorch.org/get-started/cloud-partners/

# Tutorial for those who know NumPy

https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 2.1019e-44],
        [0.0000e+00, 7.9228e+07, 8.0995e-43],
        [1.6453e+07, 8.0995e-43, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [6]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3844, 0.9176, 0.4817],
        [0.5556, 0.9145, 0.5809],
        [0.0306, 0.0562, 0.5813],
        [0.3669, 0.4373, 0.5055],
        [0.5092, 0.1875, 0.5755]])


In [7]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [10]:
x = torch.tensor([[5.5, 3],[3.1,60.3]])
print(x)

tensor([[ 5.5000,  3.0000],
        [ 3.1000, 60.3000]])


In [11]:
import numpy as np

In [12]:
x = torch.tensor(np.random.rand(3,6,2))
print(x)

tensor([[[0.2921, 0.7695],
         [0.6179, 0.2820],
         [0.9818, 0.7626],
         [0.3814, 0.0177],
         [0.8048, 0.9795],
         [0.7746, 0.7662]],

        [[0.9886, 0.5660],
         [0.5383, 0.9394],
         [0.3554, 0.4466],
         [0.5792, 0.9216],
         [0.8597, 0.8667],
         [0.7870, 0.6640]],

        [[0.9215, 0.2770],
         [0.2596, 0.4671],
         [0.5813, 0.9193],
         [0.5353, 0.3132],
         [0.8501, 0.1599],
         [0.0993, 0.0861]]], dtype=torch.float64)


In [14]:
x.size()

torch.Size([3, 6, 2])

In [15]:
# Addition: providing an output tensor as argument
result = torch.empty(5, 3)
y = torch.rand(5, 3)
x = torch.rand(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.6201, 1.6629, 1.1732],
        [0.4381, 1.2510, 1.3982],
        [0.6240, 0.4890, 1.0929],
        [0.5833, 0.9086, 0.5958],
        [1.2487, 0.5927, 1.6693]])


In [16]:
# adds x to y in place
y.add_(x)
print(y)

tensor([[0.6201, 1.6629, 1.1732],
        [0.4381, 1.2510, 1.3982],
        [0.6240, 0.4890, 1.0929],
        [0.5833, 0.9086, 0.5958],
        [1.2487, 0.5927, 1.6693]])


In [ ]:
# Any operation that mutates a tensor in-place is post-fixed with an _.
# For example: x.copy_(y), x.t_(), will change x.

In [17]:
# Resizing: If you want to resize/reshape tensor, you can use torch.view
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [18]:
# If you have a one element tensor, 
# use .item() to get the value as a Python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.5410])
-0.5410429239273071


## Converting a Torch Tensor to a NumPy Array

In [19]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [22]:
b = a.numpy()
print(b,type(b))

[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>


In [23]:
# See how the numpy array changed in value.
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically

In [24]:
# import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [26]:
a = np.ones(5)
b = torch.tensor(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [ ]:
## All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## CUDA Tensors
Tensors can be moved onto any device using the .to method.

In [27]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([0.4590], device='cuda:0')
tensor([0.4590], dtype=torch.float64)


## Next: AutoGrad
* https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html